In [135]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [136]:
data=pd.read_csv("/mnt/data/ml-platform/containers/resume_salary_intelligence/training/expected_ctc.csv")
# data.head()

In [137]:
data.shape

(25000, 29)

In [138]:
# data.info()

In [139]:
# data.describe()

In [140]:
data.columns

Index(['IDX', 'Applicant_ID', 'Total_Experience',
       'Total_Experience_in_field_applied', 'Department', 'Role', 'Industry',
       'Organization', 'Designation', 'Education', 'Graduation_Specialization',
       'University_Grad', 'Passing_Year_Of_Graduation', 'PG_Specialization',
       'University_PG', 'Passing_Year_Of_PG', 'PHD_Specialization',
       'University_PHD', 'Passing_Year_Of_PHD', 'Curent_Location',
       'Preferred_location', 'Current_CTC', 'Inhand_Offer',
       'Last_Appraisal_Rating', 'No_Of_Companies_worked',
       'Number_of_Publications', 'Certifications', 'International_degree_any',
       'Expected_CTC'],
      dtype='str')

In [141]:
data.drop("IDX",axis=1,inplace=True)
# data.head()

# Univariate Analysis:

In [142]:
# data["Applicant_ID"].unique().shape #There are multiple applicants with same application number.

In [143]:
# Box_list=['Total_Experience','Total_Experience_in_field_applied','Passing_Year_Of_PG','Passing_Year_Of_PHD','No_Of_Companies_worked','Current_CTC','Number_of_Publications','Expected_CTC']

In [144]:
# for i in Box_list:
#     print(f"Boxplot of {i}------------------------------------------------------")
#     sns.boxplot(data[i])
#     plt.xlabel(i)
#     plt.show()

In [145]:
# count_list=["Department","Role","Industry","Organization","Designation","Education","Graduation_Specialization","University_Grad","PG_Specialization","University_PG","PHD_Specialization","University_PHD","Curent_Location","Preferred_location","Inhand_Offer","Last_Appraisal_Rating","International_degree_any"]

In [146]:
# for i in count_list:
#     print(f"Countplot of {i}------------------------------------------------------")
#     sns.countplot(data,x=i)
#     plt.xticks(rotation=90)
#     plt.show()

In [147]:
# data.columns

# Bivariate Analysis:

In [148]:
cat_col=list(data.select_dtypes('object').columns)
cat_col.append("International_degree_any")

In [149]:
# for i in cat_col:
#     print(f"Boxplot of {i}")
#     sns.boxplot(data, y='Expected_CTC', x=i)
#     plt.xticks(rotation=90)
#     plt.show()

In [150]:
# elist=['Department', 'Role', 'Industry','Organization', 'Designation', 'Education','Inhand_Offer']
# for i in elist:
#     for j in elist:
#         if i!=j:
#             print(f"Countplot of {j} hue with {i}")
#             plt.figure(figsize=(15,15))
#             plt.xticks(rotation=90)
#             sns.countplot(data, x=j, hue=i)
#             plt.show()

In [151]:
# scatter_list=["Total_Experience","Passing_Year_Of_Graduation","Passing_Year_Of_PG","Passing_Year_Of_PHD"]

In [152]:
# for i in scatter_list:
#     print(f"Scatter plot of {i}")
#     sns.scatterplot(data,x=i,y="Current_CTC",hue="Expected_CTC")
#     plt.show()

In [153]:
# sns.scatterplot(data,x="Current_CTC",y="Expected_CTC")

In [154]:
# plt.figure(figsize=(10,8))
# sns.heatmap(data.corr(),annot=True,fmt=".2f")

# Missing Value Treatment

In [155]:
data.isnull().sum()

Applicant_ID                             0
Total_Experience                         0
Total_Experience_in_field_applied        0
Department                            2778
Role                                   963
Industry                               908
Organization                           908
Designation                           3129
Education                                0
Graduation_Specialization             6180
University_Grad                       6180
Passing_Year_Of_Graduation            6180
PG_Specialization                     7692
University_PG                         7692
Passing_Year_Of_PG                    7692
PHD_Specialization                   11881
University_PHD                       11881
Passing_Year_Of_PHD                  11881
Curent_Location                          0
Preferred_location                       0
Current_CTC                              0
Inhand_Offer                             0
Last_Appraisal_Rating                  908
No_Of_Companies_worked                   0
Number_of_Publications                   0
Certifications                           0
International_degree_any                 0
Expected_CTC                             0
dtype: int64

In [156]:
data["Department"].value_counts()

Department
Marketing         2379
Analytics/BI      2096
Healthcare        2062
Others            2041
Sales             1991
HR                1988
Banking           1952
Education         1948
Engineering       1937
Top Management    1632
Accounts          1118
IT-Software       1078
Name: count, dtype: int64

In [157]:
data["Department"] = data["Department"].fillna("Others")

In [158]:
data["Department"].value_counts()

Department
Others            4819
Marketing         2379
Analytics/BI      2096
Healthcare        2062
Sales             1991
HR                1988
Banking           1952
Education         1948
Engineering       1937
Top Management    1632
Accounts          1118
IT-Software       1078
Name: count, dtype: int64

In [159]:
data["Role"].value_counts()

Role
Others                  2248
Bio statistician        1913
Analyst                 1892
Project Manager         1850
Team Lead               1833
Consultant              1780
Business Analyst        1711
Sales Execituve         1574
Sales Manager           1427
Senior Researcher       1236
Financial Analyst       1182
CEO                     1149
Scientist               1139
Head                    1108
Associate                767
Data scientist           363
Principal Analyst        275
Area Sales Manager       134
Senior Analyst           128
Researcher               123
Sr. Business Analyst     114
Research Scientist        33
Professor                 33
Lab Executuve             25
Name: count, dtype: int64

In [160]:
data["Role"] = data["Role"].fillna("Others")

In [161]:
data["Industry"].value_counts()

Industry
Training      2237
IT            2228
Insurance     2219
BFSI          2207
Automobile    2202
Analytics     2201
Retail        2195
Telecom       2190
Aviation      2183
FMCG          2180
Others        2050
Name: count, dtype: int64

In [162]:
data["Organization"].value_counts()

Organization
M    1574
J    1555
P    1542
H    1532
A    1526
F    1505
G    1504
K    1503
I    1489
E    1488
B    1488
L    1484
C    1482
N    1476
D    1474
O    1470
Name: count, dtype: int64

In [163]:
data["Designation"].value_counts()

Designation
HR                    1648
Others                1647
Manager               1628
Product Manager       1626
Sr.Manager            1617
Consultant            1606
Marketing Manager     1590
Assistant Manager     1590
Data Analyst          1575
Research Analyst      1563
Medical Officer       1047
Software Developer     914
Web Designer           882
Network Engineer       862
Director               772
CA                     715
Research Scientist     537
Scientist               52
Name: count, dtype: int64

In [164]:
data["Industry"] = data["Industry"].fillna("Others")
data["Organization"] = data["Organization"].fillna("Others")
data["Designation"] = data["Designation"].fillna("Others")

In [165]:
data["Last_Appraisal_Rating"].value_counts()

Last_Appraisal_Rating
B                5501
D                4917
C                4812
A                4671
Key_Performer    4191
Name: count, dtype: int64

In [166]:
data["Last_Appraisal_Rating"] = data["Last_Appraisal_Rating"].replace("Key_Performer", 5)
data["Last_Appraisal_Rating"] = data["Last_Appraisal_Rating"].replace("A", 4)
data["Last_Appraisal_Rating"] = data["Last_Appraisal_Rating"].replace("B", 3)
data["Last_Appraisal_Rating"] = data["Last_Appraisal_Rating"].replace("C", 2)
data["Last_Appraisal_Rating"] = data["Last_Appraisal_Rating"].replace("D", 1)

In [167]:
data["Last_Appraisal_Rating"] = data["Last_Appraisal_Rating"].fillna(data["Last_Appraisal_Rating"].mean())

In [168]:
data["Last_Appraisal_Rating"].value_counts()

Last_Appraisal_Rating
3           5501
1           4917
2           4812
4           4671
5           4191
2.933878     908
Name: count, dtype: int64

In [169]:
data.isnull().sum()

Applicant_ID                             0
Total_Experience                         0
Total_Experience_in_field_applied        0
Department                               0
Role                                     0
Industry                                 0
Organization                             0
Designation                              0
Education                                0
Graduation_Specialization             6180
University_Grad                       6180
Passing_Year_Of_Graduation            6180
PG_Specialization                     7692
University_PG                         7692
Passing_Year_Of_PG                    7692
PHD_Specialization                   11881
University_PHD                       11881
Passing_Year_Of_PHD                  11881
Curent_Location                          0
Preferred_location                       0
Current_CTC                              0
Inhand_Offer                             0
Last_Appraisal_Rating                    0
No_Of_Companies_worked                   0
Number_of_Publications                   0
Certifications                           0
International_degree_any                 0
Expected_CTC                             0
dtype: int64

In [170]:
# data["Education"].value_counts()

In [171]:
# data["Graduation_Specialization"].isnull().sum()

# Outlier Treatment

In [172]:
# plt.figure(figsize=(15,15))
# sns.boxplot(data)
# plt.xticks(rotation=90)

In [173]:
for i in ["Total_Experience_in_field_applied","Certifications","International_degree_any"]:
    Q1=data[i].quantile(0.25)
    Q3=data[i].quantile(0.75)
    IQR=Q3-Q1
    data[i]=np.where(data[i]<Q1 - 1.5 * IQR,Q1,data[i])
    data[i]=np.where(data[i]>Q3 + 1.5 * IQR,Q3,data[i])

In [174]:
# plt.figure(figsize=(15,15))
# sns.boxplot(data)
# plt.xticks(rotation=90)

In [175]:
# data['Expected_CTC'].min()

In [176]:
# data['Expected_CTC'].max()

In [177]:
# data['Expected_CTC'].mean()

In [178]:
# data['Expected_CTC'].median()

In [179]:
# sns.kdeplot(data['Expected_CTC'], shade=True)

In [180]:
data.duplicated().sum()

np.int64(0)

In [181]:
data.drop(['Applicant_ID','Graduation_Specialization', 'University_Grad',
       'Passing_Year_Of_Graduation', 'PG_Specialization', 'University_PG',
       'Passing_Year_Of_PG', 'PHD_Specialization', 'University_PHD',
       'Passing_Year_Of_PHD'],axis=1,inplace=True)

In [182]:
cat_col=list(data.select_dtypes('object').columns)
num_col=list(data.select_dtypes(['int64', 'float64']).columns)

In [183]:
cat_col.append('International_degree_any')

In [184]:
num_col.remove('International_degree_any')

In [185]:
# len(num_col)

In [186]:
data=pd.get_dummies(data,columns=cat_col,drop_first=True)
# data.head()

In [187]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Columns: 121 entries, Total_Experience to Last_Appraisal_Rating_5
dtypes: bool(114), float64(2), int64(5)
memory usage: 4.1 MB

In [188]:
from scipy.stats import zscore
for i in num_col:
    data[i] = zscore(data[i])
# data.head()

In [189]:
# data.info()

In [190]:
X=data.drop('Expected_CTC',axis=1)
y=data['Expected_CTC']

In [191]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.30 , random_state=1)

In [192]:
X_train = X_train.astype(float)

In [193]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif_data = pd.DataFrame()
vif_data["feature"] = X_train.columns
vif_data["VIF"] = [variance_inflation_factor(X_train, i) for i in range(X_train.shape[1])]

In [194]:
vif_data.sort_values(by='VIF', ascending=False).head(20)

                                      feature       VIF
116  Last_Appraisal_Rating_2.9338784658807904       inf
64                        Organization_Others       inf
2                                 Current_CTC  5.406165
0                            Total_Experience  5.402313
14                          Department_Others  4.965511
75                         Designation_Others  3.961341
85                       Education_Under Grad  3.576577
27                                Role_Others  3.013241
6                     Department_Analytics/BI  2.852824
13                       Department_Marketing  2.791427
46                            Industry_Others  2.673278
11                      Department_Healthcare  2.671930
16                  Department_Top Management  2.634142
10                              Department_HR  2.526549
7                          Department_Banking  2.516174
8                        Department_Education  2.515063
15                           Department_Sales  2.480753
84                               Education_PG  2.442165
9                      Department_Engineering  2.440319
83                             Education_Grad  2.322505

In [195]:
import statsmodels.api as sm
olsmod_1 = sm.OLS(y_train, X_train)
olsres_1 = olsmod_1.fit()
print(
    "R-squared:",
    np.round(olsres_1.rsquared, 3),
    "\nAdjusted R-squared:",
    np.round(olsres_1.rsquared_adj, 3),
)

R-squared: 0.996
Adjusted R-squared: 0.996

In [196]:

X_train1=X_train.drop('Total_Experience',axis=1)
olsmod_2 = sm.OLS(y_train, X_train1)
olsres_2 = olsmod_2.fit()
print(
    "R-squared:",
    np.round(olsres_2.rsquared, 3),
   "\nAdjusted R-squared:",
   np.round(olsres_2.rsquared_adj, 3),
)

R-squared: 0.996
Adjusted R-squared: 0.996

In [197]:
vif_data = pd.DataFrame()
vif_data["feature"] = X_train1.columns
vif_data["VIF"] = [variance_inflation_factor(X_train1, i) for i in range(X_train1.shape[1])]

print(vif_data)

                                      feature       VIF
0           Total_Experience_in_field_applied  1.506355
1                                 Current_CTC  2.133669
2                      No_Of_Companies_worked  1.312630
3                      Number_of_Publications  1.113587
4                              Certifications  1.563806
..                                        ...       ...
114                   Last_Appraisal_Rating_2  1.950319
115  Last_Appraisal_Rating_2.9338784658807904       inf
116                   Last_Appraisal_Rating_3  2.104389
117                   Last_Appraisal_Rating_4  1.923033
118                   Last_Appraisal_Rating_5  2.233170

[119 rows x 2 columns]

In [198]:
vif_data.sort_values(by='VIF', ascending=False).head(20)

                                      feature       VIF
63                        Organization_Others       inf
115  Last_Appraisal_Rating_2.9338784658807904       inf
13                          Department_Others  4.894221
74                         Designation_Others  3.961186
84                       Education_Under Grad  3.153609
26                                Role_Others  3.013114
5                     Department_Analytics/BI  2.822125
12                       Department_Marketing  2.748538
45                            Industry_Others  2.673070
10                      Department_Healthcare  2.642703
15                  Department_Top Management  2.613669
7                        Department_Education  2.510250
9                               Department_HR  2.493978
6                          Department_Banking  2.489780
14                           Department_Sales  2.451462
8                      Department_Engineering  2.416461
83                               Education_PG  2.384243
118                   Last_Appraisal_Rating_5  2.233170
113                            Inhand_Offer_Y  2.181181
82                             Education_Grad  2.153384

In [199]:
X_train2=X_train1.drop('Department_Others',axis=1)
olsmod_3 = sm.OLS(y_train, X_train2)
olsres_3 = olsmod_3.fit()
print(
    "R-squared:",
    np.round(olsres_3.rsquared, 3),
   "\nAdjusted R-squared:",
   np.round(olsres_3.rsquared_adj, 3),
)

R-squared: 0.996
Adjusted R-squared: 0.996

In [200]:
vif_data2 = pd.DataFrame()
vif_data2["feature"] = X_train2.columns
vif_data2["VIF"] = [variance_inflation_factor(X_train2, i) for i in range(X_train2.shape[1])]

In [201]:
vif_data2.sort_values(by='VIF', ascending=False).head(20)

                                      feature       VIF
114  Last_Appraisal_Rating_2.9338784658807904       inf
62                        Organization_Others       inf
73                         Designation_Others  3.818400
83                       Education_Under Grad  3.133004
25                                Role_Others  2.974128
44                            Industry_Others  2.648032
82                               Education_PG  2.372137
117                   Last_Appraisal_Rating_5  2.224880
112                            Inhand_Offer_Y  2.179087
81                             Education_Grad  2.135604
1                                 Current_CTC  2.114592
115                   Last_Appraisal_Rating_3  2.094355
113                   Last_Appraisal_Rating_2  1.943249
47                          Industry_Training  1.920890
116                   Last_Appraisal_Rating_4  1.917734
68                             Designation_HR  1.908573
39                          Industry_Aviation  1.902006
17                      Role_Bio statistician  1.901209
92                    Curent_Location_Lucknow  1.900810
41                              Industry_FMCG  1.896484

In [202]:
X_train3=X_train2.drop('Designation_Others',axis=1)
olsmod_4 = sm.OLS(y_train, X_train3)
olsres_4 = olsmod_4.fit()
print(
    "R-squared:",
    np.round(olsres_4.rsquared, 3),
   "\nAdjusted R-squared:",
   np.round(olsres_4.rsquared_adj, 3),
)

R-squared: 0.996
Adjusted R-squared: 0.996

In [203]:
vif_data3 = pd.DataFrame()
vif_data3["feature"] = X_train3.columns
vif_data3["VIF"] = [variance_inflation_factor(X_train3, i) for i in range(X_train3.shape[1])]

In [204]:
vif_data3.sort_values(by='VIF', ascending=False).head(20)

                                      feature       VIF
62                        Organization_Others       inf
113  Last_Appraisal_Rating_2.9338784658807904       inf
82                       Education_Under Grad  3.083596
25                                Role_Others  2.942491
44                            Industry_Others  2.627080
81                               Education_PG  2.342756
116                   Last_Appraisal_Rating_5  2.214505
111                            Inhand_Offer_Y  2.177560
80                             Education_Grad  2.120510
1                                 Current_CTC  2.114118
114                   Last_Appraisal_Rating_3  2.084730
112                   Last_Appraisal_Rating_2  1.934426
115                   Last_Appraisal_Rating_4  1.910158
47                          Industry_Training  1.910082
39                          Industry_Aviation  1.892288
17                      Role_Bio statistician  1.884308
41                              Industry_FMCG  1.880628
91                    Curent_Location_Lucknow  1.878427
43                         Industry_Insurance  1.876953
40                              Industry_BFSI  1.874512

In [205]:
X_train4=X_train3.drop('Role_Others',axis=1)
olsmod_5 = sm.OLS(y_train, X_train4)
olsres_5 = olsmod_5.fit()
print(
    "R-squared:",
    np.round(olsres_5.rsquared, 3),
   "\nAdjusted R-squared:",
   np.round(olsres_5.rsquared_adj, 3),
)

R-squared: 0.996
Adjusted R-squared: 0.996

In [206]:
vif_data4 = pd.DataFrame()
vif_data4["feature"] = X_train4.columns
vif_data4["VIF"] = [variance_inflation_factor(X_train4, i) for i in range(X_train4.shape[1])]

In [207]:
vif_data4.sort_values(by='VIF', ascending=False).head(20)

                                      feature       VIF
112  Last_Appraisal_Rating_2.9338784658807904       inf
61                        Organization_Others       inf
81                       Education_Under Grad  3.073724
43                            Industry_Others  2.610176
80                               Education_PG  2.335570
115                   Last_Appraisal_Rating_5  2.209793
110                            Inhand_Offer_Y  2.176974
79                             Education_Grad  2.113660
1                                 Current_CTC  2.113291
113                   Last_Appraisal_Rating_3  2.077095
111                   Last_Appraisal_Rating_2  1.927184
114                   Last_Appraisal_Rating_4  1.905194
46                          Industry_Training  1.899667
38                          Industry_Aviation  1.879917
40                              Industry_FMCG  1.869563
42                         Industry_Insurance  1.864170
39                              Industry_BFSI  1.862547
45                           Industry_Telecom  1.860266
90                    Curent_Location_Lucknow  1.859999
37                        Industry_Automobile  1.856617

In [208]:
X_train5=X_train4.drop('Industry_Others',axis=1)
olsmod_6 = sm.OLS(y_train, X_train5)
olsres_6 = olsmod_6.fit()
print(
    "R-squared:",
    np.round(olsres_6.rsquared, 3),
   "\nAdjusted R-squared:",
   np.round(olsres_6.rsquared_adj, 3),
)

R-squared: 0.996
Adjusted R-squared: 0.996

In [209]:
vif_data5 = pd.DataFrame()
vif_data5["feature"] = X_train5.columns
vif_data5["VIF"] = [variance_inflation_factor(X_train5, i) for i in range(X_train5.shape[1])]

In [210]:
vif_data5.sort_values(by='VIF', ascending=False).head(20)

                                      feature       VIF
60                        Organization_Others       inf
111  Last_Appraisal_Rating_2.9338784658807904       inf
80                       Education_Under Grad  3.067876
79                               Education_PG  2.329683
114                   Last_Appraisal_Rating_5  2.207160
109                            Inhand_Offer_Y  2.176677
1                                 Current_CTC  2.111554
78                             Education_Grad  2.110813
112                   Last_Appraisal_Rating_3  2.072127
110                   Last_Appraisal_Rating_2  1.923112
113                   Last_Appraisal_Rating_4  1.900156
89                    Curent_Location_Lucknow  1.838077
108                  Preferred_location_Surat  1.834809
81                  Curent_Location_Bangalore  1.830697
86                     Curent_Location_Jaipur  1.830691
91                     Curent_Location_Mumbai  1.827208
82                Curent_Location_Bhubaneswar  1.827120
85                   Curent_Location_Guwahati  1.826414
83                    Curent_Location_Chennai  1.822043
87                     Curent_Location_Kanpur  1.817685

In [211]:
X_test.drop(["Total_Experience","Department_Others","Designation_Others","Role_Others","Industry_Others"], axis=1, inplace=True)

## Linear Regression:

In [212]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
regression_model = LinearRegression()
regression_model.fit(X_train5, y_train)

LinearRegression()

In [213]:
print('The coefficient of determination R^2 of the prediction on Train set',regression_model.score(X_train5, y_train))
print('The coefficient of determination R^2 of the prediction on Test set',regression_model.score(X_test, y_test))

The coefficient of determination R^2 of the prediction on Train set 0.9957563413134652
The coefficient of determination R^2 of the prediction on Test set 0.9958809560453615

In [214]:
print("The Root Mean Square Error (RMSE) of the model is for testing set is",np.sqrt(mean_squared_error(y_test,regression_model.predict(X_test))))

The Root Mean Square Error (RMSE) of the model is for testing set is 0.06474913358225566

## Random Forest:

In [215]:
from sklearn.ensemble import RandomForestRegressor
RF_model = RandomForestRegressor(n_estimators=100, random_state=42)
RF_model.fit(X_train5, y_train)

RandomForestRegressor(random_state=42)

In [216]:
print('The coefficient of determination R^2 of the prediction on Train set',RF_model.score(X_train5, y_train))
print('The coefficient of determination R^2 of the prediction on Test set',RF_model.score(X_test, y_test))

The coefficient of determination R^2 of the prediction on Train set 0.9997588303578389
The coefficient of determination R^2 of the prediction on Test set 0.9984739967118762

In [217]:
print("The Root Mean Square Error (RMSE) of the model is for testing set is",np.sqrt(mean_squared_error(y_test,RF_model.predict(X_test))))

The Root Mean Square Error (RMSE) of the model is for testing set is 0.03941063958285769

## Decision Tree:

In [218]:
from sklearn.tree import DecisionTreeRegressor
DT_model = DecisionTreeRegressor(random_state=42)
DT_model.fit(X_train5, y_train)

DecisionTreeRegressor(random_state=42)

In [219]:
print('The coefficient of determination R^2 of the prediction on Train set',DT_model.score(X_train5, y_train))
print('The coefficient of determination R^2 of the prediction on Test set',DT_model.score(X_test, y_test))

The coefficient of determination R^2 of the prediction on Train set 0.9999766596757377
The coefficient of determination R^2 of the prediction on Test set 0.9968779620370964

In [220]:
print("The Root Mean Square Error (RMSE) of the model is for testing set is",np.sqrt(mean_squared_error(y_test,DT_model.predict(X_test))))

The Root Mean Square Error (RMSE) of the model is for testing set is 0.05637088304545889

## Gradient Boosting:

In [221]:
from sklearn.ensemble import GradientBoostingRegressor
GB_model = GradientBoostingRegressor(n_estimators=100, random_state=42)
GB_model.fit(X_train5, y_train)

GradientBoostingRegressor(random_state=42)

In [222]:
print('The coefficient of determination R^2 of the prediction on Train set',GB_model.score(X_train5, y_train))
print('The coefficient of determination R^2 of the prediction on Test set',GB_model.score(X_test, y_test))

The coefficient of determination R^2 of the prediction on Train set 0.997947062075364
The coefficient of determination R^2 of the prediction on Test set 0.9980056089254267

In [223]:
print("The Root Mean Square Error (RMSE) of the model is for testing set is",np.sqrt(mean_squared_error(y_test,GB_model.predict(X_test))))

The Root Mean Square Error (RMSE) of the model is for testing set is 0.04505478371517897

## KNN Model:

In [224]:
from sklearn.neighbors import KNeighborsRegressor
KNN_model = KNeighborsRegressor(n_neighbors=5)
KNN_model.fit(X_train5, y_train)

KNeighborsRegressor()

In [225]:
print('The coefficient of determination R^2 of the prediction on Train set',KNN_model.score(X_train5, y_train))
print('The coefficient of determination R^2 of the prediction on Test set',KNN_model.score(X_test, y_test))

The coefficient of determination R^2 of the prediction on Train set 0.9274732356654473
The coefficient of determination R^2 of the prediction on Test set 0.8956518067500995

In [226]:
print("The Root Mean Square Error (RMSE) of the model is for testing set is",np.sqrt(mean_squared_error(y_test,KNN_model.predict(X_test))))

The Root Mean Square Error (RMSE) of the model is for testing set is 0.32589538851700417

## Ada Boosting:

In [227]:
from sklearn.ensemble import AdaBoostRegressor
base_model = DecisionTreeRegressor(max_depth=3)
ADA_model = AdaBoostRegressor(base_model, n_estimators=50, random_state=42)
ADA_model.fit(X_train5, y_train)

AdaBoostRegressor(estimator=DecisionTreeRegressor(max_depth=3), random_state=42)

In [228]:
print('The coefficient of determination R^2 of the prediction on Train set',ADA_model.score(X_train5, y_train))
print('The coefficient of determination R^2 of the prediction on Test set',ADA_model.score(X_test, y_test))

The coefficient of determination R^2 of the prediction on Train set 0.9756108498339339
The coefficient of determination R^2 of the prediction on Test set 0.9757929852847295

In [229]:
print("The Root Mean Square Error (RMSE) of the model is for testing set is",np.sqrt(mean_squared_error(y_test,ADA_model.predict(X_test))))

The Root Mean Square Error (RMSE) of the model is for testing set is 0.15696627980067845

## Grid search CV for Linear Regression:

In [230]:
# from sklearn.linear_model import Ridge
# from sklearn.model_selection import GridSearchCV

# param_grid = {
#     'alpha': [0.1, 1.0, 10.0, 100.0],
#     'solver': ['auto', 'sag', 'lsqr'],
#     'tol': [0.0001, 0.00001]
# }

# ridge = Ridge()
# grid_search = GridSearchCV(estimator=ridge, param_grid=param_grid, cv=3, n_jobs=-1, scoring='neg_mean_squared_error')
# grid_search.fit(X_train5, y_train)


# best_params = grid_search.best_params_
# best_score = -grid_search.best_score_

# print(f"Best Parameters for Ridge Regression: {best_params}")
# print(f"Best Cross-Validation Score (MSE): {best_score}")

# best_ridge_model = grid_search.best_estimator_

# print('The coefficient of determination R^2 of the prediction on Train set:', best_ridge_model.score(X_train5, y_train))
# print('The coefficient of determination R^2 of the prediction on Test set:', best_ridge_model.score(X_test, y_test))
# print("The Root Mean Square Error (RMSE) of the model for the test set is:", np.sqrt(mean_squared_error(y_test, best_ridge_model.predict(X_test))))

## Grid search CV for Random Forest:

In [231]:
# param_grid = {
#     'n_estimators': [100, 200, 300],
#     'max_features': ['auto', 'sqrt', 'log2'],
#     'max_depth': [10, 20, 30, None],
#     'min_samples_split': [2, 5, 10],
#     'min_samples_leaf': [1, 2, 4],
#     'bootstrap': [True, False]
# }

# rf = RandomForestRegressor(random_state=42)
# grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=3, n_jobs=-1, scoring='neg_mean_squared_error')
# grid_search.fit(X_train5, y_train)

# best_params = grid_search.best_params_
# best_score = -grid_search.best_score_

# print(f"Best Parameters for Random Forest: {best_params}")
# print(f"Best Cross-Validation Score (MSE): {best_score}")

# best_rf_model = grid_search.best_estimator_
# print('The coefficient of determination R^2 of the prediction on Train set:', best_rf_model.score(X_train5, y_train))
# print('The coefficient of determination R^2 of the prediction on Test set:', best_rf_model.score(X_test, y_test))
# print("The Root Mean Square Error (RMSE) of the model for the test set is:", np.sqrt(mean_squared_error(y_test, best_rf_model.predict(X_test))))

## Grid Search CV for Decision Tree:

In [232]:
# param_grid = {
#     'max_depth': [3, 5, 7, 10, None],
#     'min_samples_split': [2, 5, 10],
#     'min_samples_leaf': [1, 2, 4],
#     'max_features': ['auto', 'sqrt', 'log2', None]
# }

# regressor = DecisionTreeRegressor()
# grid_search = GridSearchCV(estimator=regressor, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)
# grid_search.fit(X_train5, y_train)

# best_params = grid_search.best_params_
# best_score = -grid_search.best_score_

# print(f"Best Parameters for Decision Tree: {best_params}")
# print(f"Best Cross-Validation Score (MSE): {best_score}")

# best_dt_model = grid_search.best_estimator_
# print('The coefficient of determination R^2 of the prediction on Train set:', best_dt_model.score(X_train5, y_train))
# print('The coefficient of determination R^2 of the prediction on Test set:', best_dt_model.score(X_test, y_test))
# print("The Root Mean Square Error (RMSE) of the model for the test set is:", np.sqrt(mean_squared_error(y_test, best_dt_model.predict(X_test))))

## Grid Search CV for Gradient Boosting:

In [233]:
# param_grid = {
#     'n_estimators': [100, 200, 300],
#     'learning_rate': [0.01, 0.1, 0.05],
#     'max_depth': [3, 4, 5],
#     'min_samples_split': [2, 5, 10],
#     'min_samples_leaf': [1, 2, 4],
#     'subsample': [0.8, 0.9, 1.0],
#     'max_features': ['auto', 'sqrt', 'log2']
# }

# gbr = GradientBoostingRegressor(random_state=42)

# grid_search = GridSearchCV(estimator=gbr, param_grid=param_grid, cv=3, n_jobs=-1, scoring='neg_mean_squared_error')
# grid_search.fit(X_train5, y_train)

# best_params = grid_search.best_params_
# best_score = -grid_search.best_score_

# print(f"Best Parameters for Gradient Boosting: {best_params}")
# print(f"Best Cross-Validation Score (MSE): {best_score}")

# best_gbr_model = grid_search.best_estimator_
# print('The coefficient of determination R^2 of the prediction on Train set:', best_gbr_model.score(X_train5, y_train))
# print('The coefficient of determination R^2 of the prediction on Test set:', best_gbr_model.score(X_test, y_test))
# print("The Root Mean Square Error (RMSE) of the model for the test set is:", np.sqrt(mean_squared_error(y_test, best_gbr_model.predict(X_test))))

In [235]:
import joblib
joblib.dump(RF_model, "/mnt/data/ml-platform/containers/resume_salary_intelligence/model/salary_prediction_model.pkl")
print("Model saved successfully")

Model saved successfully